on:
  pull_request:
    branches:
      - production
    types:
      - closed
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: changed-files
        run: echo "value=$(git diff --name-only ${{github.event.pull_request.base.sha}} HEAD | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        env:
          CHANGED_FILES: ${{steps.changed-files.outputs.value}}
        with:
          script: |
            console.log(process.env.CHANGED_FILES)
