on:
  pull_request:
    branches:
      - production
    types:
      - closed
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: previous-merge-commit
        run: echo "value=$(git log --pretty=format:"%H" --merges --first-parent -n 1 HEAD~)" >> $GITHUB_OUTPUT
      - id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: true
          base_sha: ${{steps.previous-merge-commit.outputs.value}}
